name: ${plugin.name}
main: ${plugin.groupID}.${plugin.name.lower}.${plugin.name}
version: ${plugin.version}
description: ${project.description}
website: ${plugin.url}
authors: [${plugin.author}]
commands:
  home:
    description: A command for the ${plugin.name} plugin.
    usage: /<command>
  sethome:
    description: A command for the ${plugin.name} plugin.
    usage: /<command>
    